In [2]:
import numpy as np

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [5]:
np.full(10,3)

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [6]:
L = [1,2,3,4]
a = np.array(L)

In [7]:
a[3]

np.int64(4)

In [8]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(1,15,2)

array([ 1,  3,  5,  7,  9, 11, 13])

In [10]:
np.linspace(1,50,11)

array([ 1. ,  5.9, 10.8, 15.7, 20.6, 25.5, 30.4, 35.3, 40.2, 45.1, 50. ])

In [11]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [12]:
n = np.full((5,2),5)

In [13]:
n[0,0]

np.int64(5)

In [14]:
n[:,1]

array([5, 5, 5, 5, 5])

In [15]:
np.random.seed(2) # fixes the random numbers for every computer that runs this
np.random.rand(5,2) # [0 and 1]

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [16]:
np.random.seed(2) # fixes the random numbers for every computer that runs this
np.random.randn(5,2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [17]:
np.random.seed(2) # fixes the random numbers for every computer that runs this
100 * np.random.rand(5,2) # [0 and 100]

array([[43.59949021,  2.59262318],
       [54.96624779, 43.53223926],
       [42.03678021, 33.0334821 ],
       [20.4648634 , 61.92709664],
       [29.96546737, 26.68272751]])

In [18]:
np.random.seed(2) # fixes the random numbers for every computer that runs this
np.random.randint(low = 5,high= 100,size = (5,2)) # [0 and 1]

array([[45, 20],
       [77, 27],
       [48, 87],
       [80, 12],
       [39, 54]])

In [19]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [20]:
a + 1

array([1, 2, 3, 4, 5])

In [21]:
a * 2 + 1

array([1, 3, 5, 7, 9])

In [22]:
a >= 2

array([False, False,  True,  True,  True])

In [23]:
a[a > 2]

array([3, 4])

In [24]:
a.min()

np.int64(0)

In [25]:
a.max()

np.int64(4)

In [26]:
a.mean()

np.float64(2.0)

In [27]:
n = np.random.randn(5,2)
n

array([[ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761],
       [ 0.55145404,  2.29220801],
       [ 0.04153939, -1.11792545],
       [ 0.53905832, -0.5961597 ]])

In [29]:
u = np.array([1,2,3,4])
v = np.arange(5,9)
v

array([5, 6, 7, 8])

In [30]:
u * v

array([ 5, 12, 21, 32])

In [31]:
u@v

np.int64(70)

In [32]:
u.dot(v)

np.int64(70)

In [37]:
U = np.arange(9).reshape(3,3)
U


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [39]:
b = np.arange(3)
b

array([0, 1, 2])

In [40]:
U @ b

array([ 5, 14, 23])

In [42]:
V = np.arange(10,19).reshape(3,3)
V

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [44]:
U * V # coef * coef

array([[  0,  11,  24],
       [ 39,  56,  75],
       [ 96, 119, 144]])

In [45]:
U @ V # matrix mul

array([[ 45,  48,  51],
       [162, 174, 186],
       [279, 300, 321]])

In [46]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [47]:
U

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [50]:
U[:2,:]

array([[0, 1, 2],
       [3, 4, 5]])

In [56]:
U[0,0]  = 3

In [57]:
U_inv = np.linalg.inv(U)
U_inv


array([[ 0.33333333, -0.66666667,  0.33333333],
       [-0.66666667, -1.33333333,  1.        ],
       [ 0.33333333,  1.66666667, -1.        ]])